#server:
#  port: 8080   # we'll override this on Render later

server:
  port: ${PORT:8080}  # set a dynamic port so Render can assign it

spring:
  datasource:
    url: ${DATABASE_URL}     # we'll set these as env vars
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none         # no schema yet; that's okay
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true   # <-- add
    baseline-version: 0         # <-- add (so V1 still runs)

app:
  cors:
    origins: ${CORS_ORIGINS:http://localhost:5173}

logging:
  level:
    org.springframework: INFO

#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://ep-calm-tree-adcx6pv1-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
#    username: neondb_owner
#    password: npg_lza3qi1gTbxF
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate.jdbc.time_zone: UTC
#  flyway:
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    baseline-version: 0
#
#app:
#  cors:
#    origins: http://localhost:5173
#
#logging:
#  level:
#    org.springframework: INFO
